In [1]:
import numpy as np
import pandas as pd

In [2]:
data_dictionary=pd.read_excel('Boosted Data Dictionary.xlsx')
# waveform_output=pd.read_excel('Waveform Total Output.xlsx')

waveform_output=pd.read_excel('PV Performance Parameters with BL.xlsx')

In [3]:
data_dictionary.head()

,Parent Folder,Boosted Hemorrhage,Original Folder,Original Hemorrhage,Sampled Time Point,Simulated Time Point,Hemorrhage Rate %/Time
0,ERNE99,10,ERNE35,30,10,30,1.0
1,ERNE98,10,ERNE31,30,10,30,1.0
2,ERNE97,10,ERNE29,30,10,30,1.0
3,ERNE96,10,ERNE26,30,10,30,1.0
4,ERNE95,10,ERNE20,30,10,30,1.0

In [4]:
waveform_output.head()

,Stroke Work,Stroke Volume,Ejection Fraction,Heart Rate,Cardiac Output,Elastance,Max Pressure,Min Pressure,Max Volume,Min Volume,...,ESP,EDV,EDP,Parent Folder,Time Point,Hemorrhage Level,Treatment Group,Original ERNE Data,Gender,Weight (kg)
0,2812.742020,34.772763,23.337425,95.238095,3311.691737,2.042940,73.933267,1.115725,151.667179,102.001462,...,71.038684,149.033655,4.324015,ERNE117,T0-1,10,10% None,ERNE50,1,66.5
1,2220.676751,45.147562,43.411118,82.758621,3736.349992,0.978705,50.712864,0.818257,107.783980,53.372505,...,44.186128,104.124306,1.443775,ERNE117,T29-30,10,10% None,ERNE50,1,66.5
2,2307.587555,31.081448,26.118864,146.341463,4548.504566,2.310095,73.443759,0.517030,121.921776,86.084820,...,71.801087,119.721757,1.313300,ERNE110,T0-1,10,10% Partial,ERNE21,1,72.4
3,1631.100576,25.977547,24.278081,88.235294,2292.136511,1.990654,53.728914,0.377893,115.244965,71.122495,...,51.712319,107.047534,1.633802,ERNE110,T29-30,10,10% Partial,ERNE21,1,72.4
4,3505.160857,33.399140,26.507254,90.225564,3013.456282,2.065405,77.016951,0.737255,140.152714,81.836572,...,68.982760,126.520438,4.528738,ERNE119,T0-1,10,10% Partial,ERNE53,0,69.4

### Watch out for the column titles when running this code.

In [5]:

# Merge the dataframes on 'Parent Folder'
merged_df = waveform_output.merge(data_dictionary, on='Parent Folder', how='left')

# Optionally, check if any waveform_output rows didn't find a match
unmatched = merged_df[merged_df.isnull().any(axis=1)]

# Save or use merged_df
# merged_df.to_excel('Waveform Output with Data Dictionary.xlsx', index=False)
merged_df.to_excel('PV Performance with Data Dictionary.xlsx', index=False)